version: "3"
services:
  redis:
    image: redis:latest
    container_name: assort-health-redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  web:
    build: .
    container_name: assort-health-front
    command: server
    ports:
      - 3000:3000
    depends_on:
      - redis