apiVersion: v1
kind: ConfigMap
metadata:
  name: assort-config
  namespace: {{ .Values.namespace }}
data:
  BASE_URL: {{ .Values.base_url }}
  DEEPGRAM_API_KEY: {{ .Values.deepgram_api_key }}
  OPENAI_API_KEY: {{ .Values.openai_api_key }}
  AZURE_SPEECH_KEY: {{ .Values.azure_speech_key }}
  AZURE_SPEECH_REGION: {{ .Values.azure_speech_region }}
  TWILIO_ACCOUNT_SID: {{ .Values.twilio_account_sid }}
  TWILIO_AUTH_TOKEN: {{ .Values.twilio_auth_token }}
  REDISHOST:  {{ .Values.redis_host }}
  REDISPORT: "{{ .Values.redis_port }}"
  REDISPASSWORD: {{ .Values.redis_password }}