# aws sqs receive-message --queue-url https://sqs.us-west-2.amazonaws.com/679111056995/nlp-train-discrete-krill
apiVersion: v1
kind: Namespace
metadata:
   name: {{.Values.namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: {{.Values.namespace}}
  labels:
    app: agent
spec:
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI#
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      # serviceAccountName: nlu-service-sa-1
      containers:
      - name: agent
        image: {{ .Values.image }}
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        args:
          - server
        envFrom:
          - configMapRef:
              name: assort-config
      nodeSelector:
        workload: agent
      # tolerations:
      # - key: "node.kubernetes.io/disk-pressure"
      #   operator: "Exists"
      #   effect: "NoExecute"
      #   tolerationSeconds: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: {{.Values.namespace}} 
spec:
  type: ClusterIP
  selector:
    app: agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---